yemekci/yemekci/Models/Urun.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace Yemekci.Models
{
    public class Urun
    {
        public int ID { get; set; }


        [Required(ErrorMessageResourceType = typeof(yemekci.Resources.lang), ErrorMessageResourceName = "LutfenUrunAdi")]
        public string Ad { get; set; }


        [Required(ErrorMessageResourceType = typeof(yemekci.Resources.lang), ErrorMessageResourceName = "LutfenUrunDetayi")]
        public string Detay { get; set; }


        [Required(ErrorMessageResourceType = typeof(yemekci.Resources.lang), ErrorMessageResourceName = "LutfenUrunKategorisi")]
        public string Kategori { get; set; }

        [Display(Name = "Fiyat (₺)")]

        [Required(ErrorMessageResourceType = typeof(yemekci.Resources.lang), ErrorMessageResourceName = "LutfenUrunFiyati")]
        public double Fiyat { get; set; }

        [Display(Name = "Görsel")]
        [DataType(DataType.ImageUrl, ErrorMessage = "Lütfen resim yolunuzu doğru şekilde giriniz.")]
        public string ResimYol { get; set; }


        [Required(ErrorMessageResourceType = typeof(yemekci.Resources.lang), ErrorMessageResourceName = "LutfenUrunAdet")]
        public int Adet { get; set; }
    }
}

yemekci/yemekci/Controllers/UrunsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Yemekci.DAL;
using Yemekci.Models;

namespace Yemekci.Controllers
{
    public class UrunsController : Controller
    {
        private YemekciContext db = new YemekciContext();

        // GET: Uruns
        [Filter.Admin]
        public ActionResult Index()
        {
            return View(db.Uruns.ToList());
        }

        // GET: Uruns/Details/5
        [Filter.Admin]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // GET: Uruns/Create
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Urun urun, HttpPostedFileBase resim)
        {
            if (ModelState.IsValid)
            {
                db.Uruns.Add(urun);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(urun);
        }

        // GET: Uruns/Edit/5
        [Filter.Admin]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: Uruns/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Filter.Admin]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Ad,Detay,Kategori,Fiyat,ResimYol,Adet")] Urun urun)
        {
            if (ModelState.IsValid)
            {
                db.Entry(urun).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(urun);
        }

        // GET: Uruns/Delete/5
        [Filter.Admin]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Urun urun = db.Uruns.Find(id);
            if (urun == null)
            {
                return HttpNotFound();
            }
            return View(urun);
        }

        // POST: Uruns/Delete/5
        [Filter.Admin]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Urun urun = db.Uruns.Find(id);
            db.Uruns.Remove(urun);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

yemekci/yemekci/Views/Uruns/Create.cshtml
@model Yemekci.Models.Urun

@{
    ViewBag.Title = @yemekci.Resources.lang.YeniUrunEkle;
}

<h2>@yemekci.Resources.lang.YeniYarat</h2>

@using (Html.BeginForm("Create", "Uruns", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@yemekci.Resources.lang.Urun</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kategori, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kategori, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kategori, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@yemekci.Resources.lang.Ekle class="btn btn-default" />
            </div>
        </div>
    </div>
}

yemekci/yemekci/Views/Uruns/Delete.cshtml
@model Yemekci.Models.Urun

@{
    ViewBag.Title = @yemekci.Resources.lang.Sil;
}

<h2>@yemekci.Resources.lang.Sil</h2>
<div>
    <h4>@yemekci.Resources.lang.Urun</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @yemekci.Resources.lang.Ad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @yemekci.Resources.lang.Detay
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detay)
        </dd>

        <dt>
            @yemekci.Resources.lang.Kategori
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori)
        </dd>

        <dt>
            @yemekci.Resources.lang.Fiyat
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyat)
        </dd>

        <dt>
            @yemekci.Resources.lang.ResimYol
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResimYol)
        </dd>

        <dt>
            @yemekci.Resources.lang.Adet
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adet)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value=@yemekci.Resources.lang.Sil class="btn btn-default" />
        </div>
    }
</div>

yemekci/yemekci/Views/Uruns/Details.cshtml
@model Yemekci.Models.Urun

@{
    ViewBag.Title = @yemekci.Resources.lang.Detaylar;
}

<h2>@yemekci.Resources.lang.Detaylar</h2>

<div>
    <h4>@yemekci.Resources.lang.Urun</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @yemekci.Resources.lang.Ad
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ad)
        </dd>

        <dt>
            @yemekci.Resources.lang.Detay
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Detay)
        </dd>

        <dt>
            @yemekci.Resources.lang.Kategori
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Kategori)
        </dd>

        <dt>
            @yemekci.Resources.lang.Fiyat
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fiyat)
        </dd>

        <dt>
            @yemekci.Resources.lang.ResimYol
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ResimYol)
        </dd>

        <dt>
            @yemekci.Resources.lang.Adet
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Adet)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink(@yemekci.Resources.lang.Duzenle, "Edit", new { id = Model.ID })
</p>

yemekci/yemekci/Views/Uruns/Edit.cshtml
@model Yemekci.Models.Urun

@{
    ViewBag.Title = @yemekci.Resources.lang.Duzenle;
}

<h2>@yemekci.Resources.lang.Duzenle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>@yemekci.Resources.lang.Urun</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Ad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detay, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detay, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detay, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Kategori, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kategori, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kategori, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fiyat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fiyat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fiyat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ResimYol, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ResimYol, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ResimYol, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Adet, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Adet, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Adet, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value=@yemekci.Resources.lang.Kaydet class="btn btn-default" />
            </div>
        </div>
    </div>
}

yemekci/yemekci/Views/Uruns/Index.cshtml
@model IEnumerable<Yemekci.Models.Urun>

@{
    ViewBag.Title = @yemekci.Resources.lang.Urunler;
}

<h2>@yemekci.Resources.lang.Urunler</h2>

<p>
    <a href="@Url.Action("Create")" class="btn btn-default">@yemekci.Resources.lang.YeniUrunEkle</a>
</p>
<table class="table">
    <tr>
        <th>
            @yemekci.Resources.lang.Ad
        </th>
        <th>
            @yemekci.Resources.lang.Detay
        </th>
        <th>
            @yemekci.Resources.lang.Kategori
        </th>
        <th>
            @yemekci.Resources.lang.Fiyat
        </th>
        <th>
            @yemekci.Resources.lang.ResimYol
        </th>
        <th>
            @yemekci.Resources.lang.Adet
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Ad)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Detay)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Kategori)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Fiyat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ResimYol)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Adet)
        </td>
        <td>
            @Html.ActionLink(@yemekci.Resources.lang.Duzenle, "Edit", new { id=item.ID }) |
            @Html.ActionLink(@yemekci.Resources.lang.Detaylar, "Details", new { id=item.ID }) |
            @Html.ActionLink(@yemekci.Resources.lang.Sil, "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>